apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-app
  template:
    metadata:
      labels:
        app: health-app
    spec:
      containers:
      - name: health-app
        image: health-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
