apiVersion: v1
kind: Service
metadata:
  name: health-service
spec:
  type: NodePort
  selector:
    app: health-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30036
